import crypto from 'crypto'
import QRCode from 'qrcode'

/**
 * The attendance QR code must actually be scanned every time, not just
 * known/bookmarked once — otherwise an employee could sign in or out from
 * home by revisiting /admin/my-attendance from browser history while still
 * logged in. To enforce that, the link encoded in the QR carries a
 * short-lived, server-verified token that rotates on a fixed clock (like a
 * TOTP code) rather than a bare static URL. The QR display page must be
 * shown live on a screen at the entrance — once this rotates, a printed
 * paper copy stops working, which is the point.
 */
const TOKEN_WINDOW_SECONDS = 60
// Accept the current window and the previous one, so a token generated just
// before a rotation boundary still works for the few seconds a scan, page
// load, and tap naturally take. Total validity from generation: 60-120s.
const TOKEN_TOLERANCE_WINDOWS = 2

function getQrSecret(): string {
  // Prefer a dedicated secret; NEXTAUTH_SECRET is the next best already-
  // provisioned value. DATABASE_URL is a last-resort fallback so local dev
  // never breaks for lack of a dedicated env var — set ATTENDANCE_QR_SECRET
  // explicitly in production.
  return (
    process.env.ATTENDANCE_QR_SECRET ||
    process.env.NEXTAUTH_SECRET ||
    process.env.DATABASE_URL ||
    'attendance-qr-dev-fallback-secret'
  )
}

function currentWindowIndex(): number {
  return Math.floor(Date.now() / 1000 / TOKEN_WINDOW_SECONDS)
}

function computeToken(windowIndex: number): string {
  return crypto
    .createHmac('sha256', getQrSecret())
    .update(String(windowIndex))
    .digest('hex')
    .slice(0, 20)
}

function timingSafeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a)
  const bufB = Buffer.from(b)
  if (bufA.length !== bufB.length) return false
  return crypto.timingSafeEqual(bufA, bufB)
}

/** The currently-valid token, to embed in a freshly generated QR code. */
export function generateAttendanceToken(): string {
  return computeToken(currentWindowIndex())
}

/**
 * True only if `token` matches one of the last TOKEN_TOLERANCE_WINDOWS
 * rotations — i.e. it was generated by a QR scan within roughly the last
 * minute or two, not bookmarked, reused from history, or guessed.
 */
export function verifyAttendanceToken(token: string | null | undefined): boolean {
  if (!token) return false
  const current = currentWindowIndex()
  for (let i = 0; i < TOKEN_TOLERANCE_WINDOWS; i++) {
    if (timingSafeEqual(token, computeToken(current - i))) return true
  }
  return false
}

/** Base attendance page URL, without a token — for display/informational text only. */
export function getAttendanceBaseUrl(): string {
  const base = process.env.FRONTEND_URL || process.env.NEXTAUTH_URL || 'http://localhost:3000'
  return `${base.replace(/\/$/, '')}/admin/my-attendance`
}

/** The full, currently-valid check-in URL, with a fresh rotating token attached. */
export function getAttendanceCheckInUrl(): string {
  return `${getAttendanceBaseUrl()}?t=${generateAttendanceToken()}`
}

export async function generateAttendanceQrDataUrl(): Promise<string> {
  return QRCode.toDataURL(getAttendanceCheckInUrl(), {
    errorCorrectionLevel: 'M',
    margin: 2,
    width: 480,
  })
}

export const ATTENDANCE_QR_WINDOW_SECONDS = TOKEN_WINDOW_SECONDS
